config/routes.rb
Rails.application.routes.draw do

  resource :example, only: [:index, :show], controller: 'example'

  root 'example#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController


  def index  
  end


  def show
    @images = "cats"
    respond_to do |format|
      format.html { render(layout: 'pdf') }

      format.pdf do
        pdf = Hpa::Pdf.create( 
          html: render_to_string(layout: 'pdf').to_str,
          header: render_to_string(template: 'example/header.erb', layout: 'pdf').to_str,
          footer: render_to_string(template: 'example/footer.erb', layout: 'pdf').to_str,
          header_spacing: 10,
          footer_spacing: 10,
          engine_version: 12
        )

        send_data(pdf, filename: "hpa_rails_example.pdf", type: "application/pdf", disposition: "inline")
      end

    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/example/footer.erb
<body>
  <footer>
    <div class="page">{{page}}/{{pages}}</div>
    <div class="credits">content by Fillerama // images by lorempixel</div>
  </footer>
</body>

app/views/example/index.html.erb
<header>
  <%= image_tag "hpa_200w.png" %>
  <p>HTML PDF API - Rails Example</p>
</header>

<main>
  <%= link_to "HTML Preview", example_path, class: "btn" %>
  <%= link_to "Download PDF", example_path(format: :pdf), class: "btn" %>
</main>

app/views/example/show.erb
<body class="content">

  <section> 
    <h1>Star Wars</h1>
    <p>I call it luck. Hokey religions and ancient weapons are no match for a good blaster at your side, kid. Don't be too proud of this technological terror you've constructed. The ability to destroy a planet is insignificant next to the power of the Force. The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. Hokey religions and ancient weapons are no match for a good blaster at your side, kid.</p>
    <div class="image"><img src="http://lorempixel.com/774/400/<%= @images %>" /></div>
  </section>

  <section> 
    <h2>Attack of the Clones</h2>
    <p>What!? In my experience, there is no such thing as luck. Ye-ha! The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. I suggest you try it again, Luke. This time, let go your conscious self and act on instinct. But with the blast shield down, I can't even see! How am I supposed to fight?</p>
    <ul>
      <li>Oh God, my uncle. How am I ever gonna explain this?</li>
      <li>But with the blast shield down, I can't even see! How am I supposed to fight?</li>
      <li>All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it?</li>
    </ul>
  </section>

  <section> 
    <h3>Knights of the Old Republic</h3>
    <p>Ye-ha! But with the blast shield down, I can't even see! How am I supposed to fight? The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. I can't get involved! I've got work to do! It's not that I like the Empire, I hate it, but there's nothing I can do about it right now. It's such a long way from here.</p>
  </section>
  
  <section> 
    <h3>The Battle for Endor</h3>
    <p>I need your help, Luke. She needs your help. I'm getting too old for this sort of thing. You don't believe in the Force, do you? I care. So, what do you think of her, Han? I find your lack of faith disturbing.</p>
    <ol>
      <li>All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it?</li>
      <li>I have traced the Rebel spies to her. Now she is my only link to finding their secret base.</li>
      <li>You don't believe in the Force, do you?</li>
      <li>I need your help, Luke. She needs your help. I'm getting too old for this sort of thing.</li>
      <li>Leave that to me. Send a distress signal, and inform the Senate that all on board were killed.</li>
    </ol>
  </section>

  <section> 
    <h2>The Phantom Menace</h3>
    <div class="image fl"><img src="http://lorempixel.com/400/280/<%= @images %>" /></div>
    <p>But with the blast shield down, I can't even see! How am I supposed to fight? I have traced the Rebel spies to her. Now she is my only link to finding their secret base. Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money. Escape is not his plan. I must face him, alone.</p>
    <p>A tremor in the Force. The last time I felt it was in the presence of my old master. He is here. I call it luck. What good is a reward if you ain't around to use it? Besides, attacking that battle station ain't my idea of courage. It's more like&hellip;suicide.</p>
    <p>Look, I can take you as far as Anchorhead. You can get a transport there to Mos Eisley or wherever you're going. I care. So, what do you think of her, Han? I find your lack of faith disturbing. I need your help, Luke. She needs your help. I'm getting too old for this sort of thing. What good is a reward if you ain't around to use it? Besides, attacking that battle station ain't my idea of courage. It's more like&hellip;suicide.</p>
    <p>All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it? The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There'll be no one to stop us this time! But with the blast shield down, I can't even see! How am I supposed to fight?</p>
    <p>I don't know what you're talking about. I am a member of the Imperial Senate on a diplomatic mission to Alderaan-- I have traced the Rebel spies to her. Now she is my only link to finding their secret base. Escape is not his plan. I must face him, alone.</p>
    <p>You are a part of the Rebel Alliance and a traitor! Take her away! Look, I can take you as far as Anchorhead. You can get a transport there to Mos Eisley or wherever you're going. Don't be too proud of this technological terror you've constructed. The ability to destroy a planet is insignificant next to the power of the Force. You don't believe in the Force, do you? You don't believe in the Force, do you?</p>
  </section>
  
  <section> 
    <h2>A New Hope</h2>
    <p>Don't be too proud of this technological terror you've constructed. The ability to destroy a planet is insignificant next to the power of the Force. He is here. You're all clear, kid. Let's blow this thing and go home! Leave that to me. Send a distress signal, and inform the Senate that all on board were killed.</p>
    <p>The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. What!? I want to come with you to Alderaan. There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me. I'm trying not to, kid. She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There'll be no one to stop us this time! I find your lack of faith disturbing.</p>
    <div class="image fr"><img src="http://lorempixel.com/400/220/<%= @images %>" /></div>
    <p>Alderaan? I'm not going to Alderaan. I've got to go home. It's late, I'm in for it as it is. As you wish. I want to come with you to Alderaan. There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me. I find your lack of faith disturbing.</p>
    <p>Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money. The Force is strong with this one. I have you now. Hokey religions and ancient weapons are no match for a good blaster at your side, kid. Your eyes can deceive you. Don't trust them.</p>
    <p>I care. So, what do you think of her, Han? I find your lack of faith disturbing. But with the blast shield down, I can't even see! How am I supposed to fight? What?! Look, I can take you as far as Anchorhead. You can get a transport there to Mos Eisley or wherever you're going. Dantooine. They're on Dantooine.</p>
    <p>Escape is not his plan. I must face him, alone. All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it? Hey, Luke! May the Force be with you.</p>
    <p>I need your help, Luke. She needs your help. I'm getting too old for this sort of thing. All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it? All right. Well, take care of yourself, Han. I guess that's what you're best at, ain't it?</p>
    <p>The more you tighten your grip, Tarkin, the more star systems will slip through your fingers. I want to come with you to Alderaan. There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me. The plans you refer to will soon be back in our hands. In my experience, there is no such thing as luck. Hey, Luke! May the Force be with you.</p>
    <p>Ye-ha! I don't know what you're talking about. I am a member of the Imperial Senate on a diplomatic mission to Alderaan-- Don't act so surprised, Your Highness. You weren't on any mercy mission this time. Several transmissions were beamed to this ship by Rebel spies. I want to know what happened to the plans they sent you.</p>
    <p>No! Alderaan is peaceful. We have no weapons. You can't possibly&hellip; What?! I want to come with you to Alderaan. There's nothing for me here now. I want to learn the ways of the Force and be a Jedi, like my father before me. Oh God, my uncle. How am I ever gonna explain this? The Force is strong with this one. I have you now.</p>
  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HTML PDF API - Rails Example</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pdf.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HTML PDF API - Rails Example</title>
    <style type="text/css">
      body {
        color: #555;
        background: #FFFFFF; 
        font-family: Arial, sans-serif; 
        font-size: 16px; 
        width: 21cm;  
        margin: 0 auto; 
      }
      section, p { page-break-inside: avoid; }
      h1, h2, h3, h4 { font-weight: normal; color: #049CDB; margin: 1.8em 0 0.8em; }
      h1 { background: #049CDB; color: #fff; padding: 4px 8px; }
      h2 { border-bottom: 2px solid #049CDB; }
      ul, ol { color: #777; }
      body.content { height: 29.7cm; }
      body.content p::first-letter { font-size: 1.1em; }
      img { vertical-align: middle; }
      header { color: #404040; border-bottom: 1px solid #049CDB; padding: 10px 0; position: relative; } 
      header p { position: absolute; bottom: 10px; right: 0; font-size: 20px; margin: 0; }
      .image { border: 10px solid #eee; }
      .image.fl { margin: 0 14px 10px 0; float: left; }
      .image.fr { margin: 0 0 10px 14px; float: right; }
      footer  {border-top: 1px solid #049CDB; padding: 10px 0; }
      footer .page {float: right; color: #049CDB; font-size: 14px; }
      footer .credits { color: #999; font-size: 12px; }
    </style>
  </head>
  <%= yield %>
</html>